### ISSUE TITLE
Aircraft Query

### ISSUE THREAD

**Issue by SammySkycrafts** [FGMEMBERS/C-5#3]
Where did you get the original aircraft from - when it was imported in commit #b12227e3b2472a0f4b78e6e4ed4baa0fac9a2f9b

**Comment by IAHM-COL** [comment]
There was a zip file since years no longer existing. I don't know of any other source for this at the moment -- Sorry to bear bad news

**Comment by IAHM-COL** [comment]
@SammySkycrafts 

Try https://github.com/FGMEMBERS/C-5/archive/b12227e3b2472a0f4b78e6e4ed4baa0fac9a2f9b.zip
that should be the original zip content
